language: php
php:
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"
before_install:
  - if [[ $HHVM == true ]]; then sudo apt-get update; fi
  - if [[ $HHVM == true ]]; then sudo apt-get install hhvm=3.\*; fi
before_script:
  - composer install
after_script:
  - php vendor/bin/php-coveralls -v
dist: trusty
sudo: required
matrix:
  include:
    - php: hhvm
      env: HHVM=true